# Generated by Django 4.1 on 2025-01-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='sort_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='title_kana',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
