# Generated by Django 4.1 on 2025-01-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='initial',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_type',
            field=models.IntegerField(choices=[(0, 'OP'), (1, 'ED'), (2, '挿入歌')], default=0),
        ),
    ]
