# Generated by Django 4.1 on 2024-12-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_tracker', '0002_anime_genres_anime_seasons_anime_studios_anime_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasons',
            name='season',
            field=models.IntegerField(choices=[(0, '冬'), (1, '春'), (2, '夏'), (3, '秋')]),
        ),
    ]
