# Generated by Django 4.1 on 2025-01-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_tracker', '0002_anime_initial_alter_song_song_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='row_initial',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
