# Generated by Django 4.1 on 2024-12-28 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime_tracker', '0003_alter_seasons_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('song_type', models.IntegerField(choices=[(0, 'OP'), (1, 'ED'), (2, 'Insert')], default=0)),
                ('artists', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('voice_actor', models.CharField(max_length=255)),
                ('anime_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_set', to='anime_tracker.anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='characters',
            field=models.ManyToManyField(related_name='animes', to='anime_tracker.character'),
        ),
        migrations.AddField(
            model_name='anime',
            name='songs',
            field=models.ManyToManyField(related_name='animes', to='anime_tracker.song'),
        ),
    ]
