# Generated by Django 4.1 on 2025-01-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_tracker', '0003_alter_anime_sort_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='sort_key',
        ),
    ]
